/**
 * مطالع الأثمان الأربعمائة والثمانين (480 ثمناً) حسب رواية قالون عن نافع — تقسيم وليد النائحي.
 * استُخرجت أرقام الآيات آلياً بمطابقة نص كل مطلع مع نص القرآن الكريم الفعلي برواية قالون
 * (مصدر: quran-api لـ fawazahmed0، نسخة "ara-quranqaloon")، ثم رُوجعت يدوياً كل حالة لم تُطابَق
 * تلقائياً، وتحققنا من تطابق تسلسلها الكامل تصاعدياً بلا أي تراجع، وقُوبلت أيضاً بمطالع الأحزاب
 * الستين المستخرجة بشكل مستقل (lib/quran/hizb.ts) فتطابقت في كل نقطة تقاطع بينهما.
 * حقل text نص المطلع نفسه (كما كُتب يدوياً)، يُستخدم فقط لعرضه في منتقي الواجهة حتى يتعرّف
 * المدرس على الثمن من كلماته لا من رقم الآية وحده.
 */
import { SURAHS } from "@/lib/quran/surahs";

export type ThumnStart = {
  thumn: number;
  surahNumber: number;
  ayah: number;
  text: string;
};

export const THUMN_STARTS: ThumnStart[] = [
  { thumn: 1, surahNumber: 1, ayah: 2, text: "الحمد لله رب العالمين" },
  { thumn: 2, surahNumber: 2, ayah: 14, text: "وإذا لقوا الذين آمنوا قالوا آمنا وإذا خلوا إلى" },
  { thumn: 3, surahNumber: 2, ayah: 26, text: "إن الله لا يستحيي أن يضرب مثلا ما بعوضة" },
  { thumn: 4, surahNumber: 2, ayah: 34, text: "وإذ قلنا للملائكة اسجدوا لآدم فسجدوا" },
  { thumn: 5, surahNumber: 2, ayah: 44, text: "أتأمرون الناس بالبر وتنسون أنفسكم" },
  { thumn: 6, surahNumber: 2, ayah: 54, text: "وإذ قال موسى لقومه يا قوم إنكم ظلمتم" },
  { thumn: 7, surahNumber: 2, ayah: 60, text: "وإذ استسقى موسى لقومه فقلنا اضرب" },
  { thumn: 8, surahNumber: 2, ayah: 67, text: "وإذ قال موسى لقومه إن الله يأمركم أن تذبحوا" },
  { thumn: 9, surahNumber: 2, ayah: 76, text: "وإذا لقوا الذين آمنوا قالوا آمنا وإذا خلا بعضهم" },
  { thumn: 10, surahNumber: 2, ayah: 85, text: "وإن يأتوكم أسارى تفادوهم" },
  { thumn: 11, surahNumber: 2, ayah: 92, text: "ولقد جاءكم موسى بالبينات ثم اتخذتم العجل" },
  { thumn: 12, surahNumber: 2, ayah: 102, text: "واتبعوا ما تتلوا الشياطين على ملك سليمان" },
  { thumn: 13, surahNumber: 2, ayah: 106, text: "ما ننسخ من آية أو ننسها" },
  { thumn: 14, surahNumber: 2, ayah: 115, text: "ولله المشرق والمغرب" },
  { thumn: 15, surahNumber: 2, ayah: 124, text: "وإذ ابتلى إبراهيم ربه بكلمات فأتمهن" },
  { thumn: 16, surahNumber: 2, ayah: 133, text: "أم كنتم شهداء إذ حضر يعقوب الموت" },
  { thumn: 17, surahNumber: 2, ayah: 142, text: "سيقول السفهاء من الناس ما ولاهم عن قبلتهم" },
  { thumn: 18, surahNumber: 2, ayah: 148, text: "ولكل وجهة هو موليها فاستبقوا الخيرات" },
  { thumn: 19, surahNumber: 2, ayah: 158, text: "إن الصفا والمروة من شعائر الله" },
  { thumn: 20, surahNumber: 2, ayah: 168, text: "يا أيها الناس كلوا مما في الأرض حلالا طيبا" },
  { thumn: 21, surahNumber: 2, ayah: 177, text: "ليس البر أن تولوا وجوهكم قبل المشرق" },
  { thumn: 22, surahNumber: 2, ayah: 185, text: "شهر رمضان الذي أنزل فيه القرءان" },
  { thumn: 23, surahNumber: 2, ayah: 189, text: "يسألونك عن الأهلة قل هي مواقيت" },
  { thumn: 24, surahNumber: 2, ayah: 197, text: "الحج أشهر معلومات" },
  { thumn: 25, surahNumber: 2, ayah: 203, text: "واذكروا الله في أيام معدودات" },
  { thumn: 26, surahNumber: 2, ayah: 213, text: "كان الناس أمة واحدة فبعث الله النبيئين" },
  { thumn: 27, surahNumber: 2, ayah: 219, text: "يسألونك عن الخمر والميسر" },
  { thumn: 28, surahNumber: 2, ayah: 228, text: "والمطلقات يتربصن بأنفسهن ثلاثة قروء" },
  { thumn: 29, surahNumber: 2, ayah: 233, text: "والوالدات يرضعن أولادهن حولين كاملين" },
  { thumn: 30, surahNumber: 2, ayah: 236, text: "لا جناح عليكم إن طلقتم النساء ما لم تمسوهن" },
  { thumn: 31, surahNumber: 2, ayah: 243, text: "ألم تر إلى الذين خرجوا من ديارهم وهم ألوف" },
  { thumn: 32, surahNumber: 2, ayah: 247, text: "وقال لهم نبيئهم إن آية ملكه أن يأتيكم التابوت" },
  { thumn: 33, surahNumber: 2, ayah: 253, text: "تلك الرسل فضلنا بعضهم على بعض" },
  { thumn: 34, surahNumber: 2, ayah: 258, text: "ألم تر إلى الذي حاج إبراهيم في ربه" },
  { thumn: 35, surahNumber: 2, ayah: 263, text: "قول معروف ومغفرة" },
  { thumn: 36, surahNumber: 2, ayah: 267, text: "يا أيها الذين آمنوا أنفقوا من طيبات ما كسبتم" },
  { thumn: 37, surahNumber: 2, ayah: 272, text: "ليس عليك هداهم ولكن الله يهدي من يشاء" },
  { thumn: 38, surahNumber: 2, ayah: 282, text: "يا أيها الذين آمنوا إذا تداينتم بدين" },
  { thumn: 39, surahNumber: 2, ayah: 283, text: "وإن كنتم على سفر" },
  { thumn: 40, surahNumber: 3, ayah: 5, text: "إن الله لا يخفى عليه شيء" },
  { thumn: 41, surahNumber: 3, ayah: 15, text: "قل أؤنبئكم بخير من ذالكم" },
  { thumn: 42, surahNumber: 3, ayah: 26, text: "قل اللهم مالك الملك تؤتي الملك من تشاء" },
  { thumn: 43, surahNumber: 3, ayah: 33, text: "إن الله اصطفى آدم ونوحا وآل إبراهيم" },
  { thumn: 44, surahNumber: 3, ayah: 42, text: "وإذ قالت الملائكة يا مريم إن الله اصطفاك" },
  { thumn: 45, surahNumber: 3, ayah: 52, text: "فلما أحس عيسى منهم الكفر قال من أنصاري" },
  { thumn: 46, surahNumber: 3, ayah: 64, text: "قل يا أهل الكتاب تعالوا إلى كلمة سواء" },
  { thumn: 47, surahNumber: 3, ayah: 75, text: "ومن أهل الكتاب من إن تأمنه بقنطار" },
  { thumn: 48, surahNumber: 3, ayah: 83, text: "أفغير دين الله تبغون وله أسلم" },
  { thumn: 49, surahNumber: 3, ayah: 92, text: "لن تنالوا البر حتى تنفقوا مما تحبون" },
  { thumn: 50, surahNumber: 3, ayah: 104, text: "ولتكن منكم أمة يدعون إلى الخير" },
  { thumn: 51, surahNumber: 3, ayah: 113, text: "ليسوا سواء من أهل الكتاب أمة قائمة" },
  { thumn: 52, surahNumber: 3, ayah: 121, text: "وإذ غدوت من أهلك تبوئ المؤمنين" },
  { thumn: 53, surahNumber: 3, ayah: 133, text: "سارعوا إلى مغفرة من ربكم وجنة عرضها" },
  { thumn: 54, surahNumber: 3, ayah: 144, text: "وما محمد إلا رسول قد خلت من قبله الرسل" },
  { thumn: 55, surahNumber: 3, ayah: 153, text: "إذ تصعدون ولا تلوون على أحد" },
  { thumn: 56, surahNumber: 3, ayah: 160, text: "إن ينصركم الله فلا غالب لكم" },
  { thumn: 57, surahNumber: 3, ayah: 171, text: "يستبشرون بنعمة من الله وفضل" },
  { thumn: 58, surahNumber: 3, ayah: 179, text: "ما كان الله ليذر المؤمنين" },
  { thumn: 59, surahNumber: 3, ayah: 186, text: "لتبلون في أموالكم وأنفسكم ولتسمعن" },
  { thumn: 60, surahNumber: 3, ayah: 195, text: "فاستجاب لهم ربهم أني لا أضيع" },
  { thumn: 61, surahNumber: 4, ayah: 6, text: "وابتلوا اليتامى حتى إذا بلغوا النكاح" },
  { thumn: 62, surahNumber: 4, ayah: 11, text: "يوصيكم الله في أولادكم للذكر مثل حذ" },
  { thumn: 63, surahNumber: 4, ayah: 13, text: "تلك حدود الله ومن يطع الله ورسوله" },
  { thumn: 64, surahNumber: 4, ayah: 19, text: "يا أيها الذين آمنوا لا يحل لكم أن ترثوا" },
  { thumn: 65, surahNumber: 4, ayah: 24, text: "والمحصنات من النساء إلا ما ملكت أيمانكم" },
  { thumn: 66, surahNumber: 4, ayah: 31, text: "إن تجتنبوا كبائر ما تنهون نكفر عنكم سيئاتكم" },
  { thumn: 67, surahNumber: 4, ayah: 36, text: "واعبدوا الله ولا تشركوا به شيئا" },
  { thumn: 68, surahNumber: 4, ayah: 47, text: "يا أيها الذين أوتوا الكتاب آمنوا بما نزلنا" },
  { thumn: 69, surahNumber: 4, ayah: 58, text: "إن الله يأمركم أن تؤدوا الأمانات" },
  { thumn: 70, surahNumber: 4, ayah: 64, text: "وما أرسلنا من رسول إلا ليطاع بإذن الله" },
  { thumn: 71, surahNumber: 4, ayah: 74, text: "فليقاتل في سبيل الله الذي يشرون" },
  { thumn: 72, surahNumber: 4, ayah: 78, text: "أينما تكونوا يدرككم الموت" },
  { thumn: 73, surahNumber: 4, ayah: 87, text: "الله لا إله إلا هو ليجمنعكم" },
  { thumn: 74, surahNumber: 4, ayah: 93, text: "ومن يقتل مؤمنا متعمدا فجزاؤه جهنم" },
  { thumn: 75, surahNumber: 4, ayah: 100, text: "ومن يهاجر في سبيل الله يجد" },
  { thumn: 76, surahNumber: 4, ayah: 105, text: "إنا أنزلنا إليك الكتاب بالحق لتحكم بين الناس" },
  { thumn: 77, surahNumber: 4, ayah: 114, text: "لا خير في كثير من نجواهم إلا" },
  { thumn: 78, surahNumber: 4, ayah: 123, text: "ليس بأمانيكم ولا أماني أهل الكتاب" },
  { thumn: 79, surahNumber: 4, ayah: 130, text: "وإن يتفرقا يغن الله كلا من سعته" },
  { thumn: 80, surahNumber: 4, ayah: 138, text: "بشر المنافقين بأن لهم عذابا أليما" },
  { thumn: 81, surahNumber: 4, ayah: 148, text: "لا يحب الله الجهر بالسوء من القول إلا" },
  { thumn: 82, surahNumber: 4, ayah: 159, text: "وإن من أهل الكتاب إلا ليؤمنن به قبل موته" },
  { thumn: 83, surahNumber: 4, ayah: 166, text: "لكن الله يشهد بما أنزل إليك أنزله بعلمه" },
  { thumn: 84, surahNumber: 4, ayah: 172, text: "لن يستنكف المسيح أن يكون عبدا لله" },
  { thumn: 85, surahNumber: 5, ayah: 3, text: "حرمت عليكم الميتة والدم ولحم الخنزير" },
  { thumn: 86, surahNumber: 5, ayah: 6, text: "يا أيها الذين آمنوا إذا قمتم إلى الصلاة" },
  { thumn: 87, surahNumber: 5, ayah: 12, text: "ولقد أخذ الله ميثاق بني إسرائيل وبعثنا" },
  { thumn: 88, surahNumber: 5, ayah: 17, text: "لقد كفر الذين قالوا إن الله هو المسيح" },
  { thumn: 89, surahNumber: 5, ayah: 23, text: "قال رجلان من الذين يخافون" },
  { thumn: 90, surahNumber: 5, ayah: 32, text: "من أجل ذلك كتبنا على بني إسرائيل أنه" },
  { thumn: 91, surahNumber: 5, ayah: 41, text: "يا أيها الرسول لا يحزنك الذين يسارعون" },
  { thumn: 92, surahNumber: 5, ayah: 45, text: "وكتبنا عليهم فيها أن النفس بالنفس" },
  { thumn: 93, surahNumber: 5, ayah: 49, text: "وأن احكم بينهم بما أنزل الله" },
  { thumn: 94, surahNumber: 5, ayah: 59, text: "قل يا أهل الكتاب هل تنقمون منا إلا أن آمنا" },
  { thumn: 95, surahNumber: 5, ayah: 67, text: "يا أيها الرسول بلغ ما أنزل إليك من ربك" },
  { thumn: 96, surahNumber: 5, ayah: 75, text: "ما المسيح ابن مريم إلا رسول" },
  { thumn: 97, surahNumber: 5, ayah: 82, text: "لتجدن أشد الناس عداوة للذين آمنوا" },
  { thumn: 98, surahNumber: 5, ayah: 90, text: "يا أيها الذين آمنوا إنما الخمر والميسر" },
  { thumn: 99, surahNumber: 5, ayah: 97, text: "جعل الله الكعبة البيت الحرام" },
  { thumn: 100, surahNumber: 5, ayah: 106, text: "يا أيها الذين آمنوا شهادة بينكم إذا حضر" },
  { thumn: 101, surahNumber: 5, ayah: 111, text: "وإذ أوحيت إلى الحواريين أن آمنوا بي" },
  { thumn: 102, surahNumber: 6, ayah: 1, text: "الحمد لله الذي خلق السماوات والأرض" },
  { thumn: 103, surahNumber: 6, ayah: 13, text: "وله ما سكن في الليل والنهار وهو السميع العليم" },
  { thumn: 104, surahNumber: 6, ayah: 25, text: "ومنهم من يستمع إليك وجعلنا على قلوبهم" },
  { thumn: 105, surahNumber: 6, ayah: 36, text: "إنما يستجيب الذين يسمعون" },
  { thumn: 106, surahNumber: 6, ayah: 50, text: "قل لا أقول لكم عندي خزائن الله" },
  { thumn: 107, surahNumber: 6, ayah: 59, text: "وعنده مفاتح الغيب لا يعلمها إلا هو" },
  { thumn: 108, surahNumber: 6, ayah: 70, text: "وذر الذين اتخذوا دينهم لعبا ولهوا" },
  { thumn: 109, surahNumber: 6, ayah: 80, text: "وحاجه قومه قال أتحاجوني في الله" },
  { thumn: 110, surahNumber: 6, ayah: 91, text: "وما قدروا الله حق قدره إذ قالوا ما أنزل الله" },
  { thumn: 111, surahNumber: 6, ayah: 95, text: "إن الله فالق الحب والنوى" },
  { thumn: 112, surahNumber: 6, ayah: 100, text: "وجعلوا لله شركاء الجن وخلقهم" },
  { thumn: 113, surahNumber: 6, ayah: 111, text: "ولو أننا نزلنا إليهم الملائكة وكلمهم الموتى" },
  { thumn: 114, surahNumber: 6, ayah: 120, text: "وذروا ظاهر الإثم وباطنه" },
  { thumn: 115, surahNumber: 6, ayah: 127, text: "لهم دار السلام عند ربهم وهو وليهم" },
  { thumn: 116, surahNumber: 6, ayah: 136, text: "وجعلوا لله مما ذرأ من الحرث والأنعام نصيبا" },
  { thumn: 117, surahNumber: 6, ayah: 141, text: "وهو الذي أنشأ جنات معروشات" },
  { thumn: 118, surahNumber: 6, ayah: 145, text: "قل لا أجد في ما أوحي إلي محرما" },
  { thumn: 119, surahNumber: 6, ayah: 151, text: "قل تعالوا أتلو ما حرم ربكم عليكم" },
  { thumn: 120, surahNumber: 6, ayah: 158, text: "هل ينظرون إلا أن تأتيهم الملائكة" },
  { thumn: 121, surahNumber: 7, ayah: 1, text: "ألمص كتاب أنزل إليك فلا يكن في صدرك" },
  { thumn: 122, surahNumber: 7, ayah: 19, text: "ويا آدم اسكن أنت وزوجك الجنة" },
  { thumn: 123, surahNumber: 7, ayah: 29, text: "قل أمر ربي بالقسط وأقيموا وجوهكم" },
  { thumn: 124, surahNumber: 7, ayah: 38, text: "قال ادخلوا في أمم قد خلت من قبلكم" },
  { thumn: 125, surahNumber: 7, ayah: 47, text: "وإذا صرفت أبصارهم تلقا أصحاب النار" },
  { thumn: 126, surahNumber: 7, ayah: 55, text: "ادعوا ربكم تضرعا وخفية" },
  { thumn: 127, surahNumber: 7, ayah: 65, text: "وإلى عاد أخاهم هودا قال يا قوم اعبدوا الله" },
  { thumn: 128, surahNumber: 7, ayah: 75, text: "قال الملأ الذين استكبروا من قومه للذين" },
  { thumn: 129, surahNumber: 7, ayah: 88, text: "قال الملأ الذين استكبروا من قومه لنخرجنك" },
  { thumn: 130, surahNumber: 7, ayah: 100, text: "أولم يهد للذين يرثون الأرض" },
  { thumn: 131, surahNumber: 7, ayah: 117, text: "وأوحينا إلى موسى أن ألق عصاك" },
  { thumn: 132, surahNumber: 7, ayah: 132, text: "وقالوا مهما تأتنا به من آية لتسحرنا بها" },
  { thumn: 133, surahNumber: 7, ayah: 142, text: "وواعدنا موسى ثلاثين ليلة" },
  { thumn: 134, surahNumber: 7, ayah: 148, text: "واتخذ قوم موسى من بعده من حليهم" },
  { thumn: 135, surahNumber: 7, ayah: 156, text: "واكتب لنا في هذه الدنيا حسنة" },
  { thumn: 136, surahNumber: 7, ayah: 163, text: "وسئلهم عن القرية" },
  { thumn: 137, surahNumber: 7, ayah: 171, text: "وإذ نتقنا الجبل فوقهم كأنه ظلة" },
  { thumn: 138, surahNumber: 7, ayah: 180, text: "ولله الأسماء الحسنى فادعوه بها" },
  { thumn: 139, surahNumber: 7, ayah: 188, text: "قل لا أملك لنفسي نفعا ولا ضرا إلا" },
  { thumn: 140, surahNumber: 7, ayah: 199, text: "خذ العفو وأمر بالعرف" },
  { thumn: 141, surahNumber: 8, ayah: 5, text: "كما أخرجك ربك من بيتك بالحق" },
  { thumn: 142, surahNumber: 8, ayah: 12, text: "إذ يوحي ربك إلى الملائكة" },
  { thumn: 143, surahNumber: 8, ayah: 22, text: "إن شر الدواب عند الله الصم البكم" },
  { thumn: 144, surahNumber: 8, ayah: 32, text: "وإذ قالوا اللهم إن كان هذا هو الحق" },
  { thumn: 145, surahNumber: 8, ayah: 41, text: "واعلموا أنما غنمتم من شيء" },
  { thumn: 146, surahNumber: 8, ayah: 49, text: "إذ يقول المنافقون والذي في قلوبهم" },
  { thumn: 147, surahNumber: 8, ayah: 60, text: "وأعدوا لهم ما استطعتم من قوة" },
  { thumn: 148, surahNumber: 8, ayah: 72, text: "إن الذين آمنوا وهاجروا وجاهدوا" },
  { thumn: 149, surahNumber: 9, ayah: 5, text: "فإذا انسلخ الأشهر الحرم فاقتلوا" },
  { thumn: 150, surahNumber: 9, ayah: 12, text: "وإن نكثوا أيمانهم من بعد عهدهم" },
  { thumn: 151, surahNumber: 9, ayah: 19, text: "أجعلتم سقاية الحاج" },
  { thumn: 152, surahNumber: 9, ayah: 25, text: "لقد نصركم الله في مواطن كثيرة" },
  { thumn: 153, surahNumber: 9, ayah: 34, text: "يا أيها الذين آمنوا إن كثيرا من الأحبار" },
  { thumn: 154, surahNumber: 9, ayah: 40, text: "إلا تنصروه فقد نصره الله" },
  { thumn: 155, surahNumber: 9, ayah: 46, text: "ولو أرادوا الخروج لأعدوا له عدة" },
  { thumn: 156, surahNumber: 9, ayah: 54, text: "وما منعهم أن تقبل منهم نفقاتهم" },
  { thumn: 157, surahNumber: 9, ayah: 61, text: "ومنهم الذين يؤذون النبيء ويقولون هو أذن" },
  { thumn: 158, surahNumber: 9, ayah: 70, text: "ألم يأتهم نبأ الذين من قبلهم قوم نوح" },
  { thumn: 159, surahNumber: 9, ayah: 75, text: "ومنهم من عاهد الله لئن آتانا من فضله" },
  { thumn: 160, surahNumber: 9, ayah: 84, text: "ولا تصل على أحد منهم مات أبدا" },
  { thumn: 161, surahNumber: 9, ayah: 93, text: "إنما السبيل على الذين يستأذنونك وهم أغنياء" },
  { thumn: 162, surahNumber: 9, ayah: 101, text: "وممن حولكم من الأعراب منافقون" },
  { thumn: 163, surahNumber: 9, ayah: 111, text: "إن الله اشترى من المؤمنين أنفسهم" },
  { thumn: 164, surahNumber: 9, ayah: 117, text: "لقد تاب الله على النبيء والمهاجرين" },
  { thumn: 165, surahNumber: 9, ayah: 123, text: "يا أيها الذين ءامنوا قاتلوا الذين يلونكم" },
  { thumn: 166, surahNumber: 10, ayah: 3, text: "إن ربكم الله الذي خلق السماوات" },
  { thumn: 167, surahNumber: 10, ayah: 11, text: "ولو يعجل الله للناس الشر استعجالهم" },
  { thumn: 168, surahNumber: 10, ayah: 19, text: "وما كان الناس إلا أمة واحدة فاختلفوا" },
  { thumn: 169, surahNumber: 10, ayah: 26, text: "للذين أحسنوا الحسنى وزيادة" },
  { thumn: 170, surahNumber: 10, ayah: 37, text: "وما كان هذا القرآن أن يفترى من دون الله" },
  { thumn: 171, surahNumber: 10, ayah: 49, text: "قل لا أملك لنفسي ضرا ولا نفعا إلا" },
  { thumn: 172, surahNumber: 10, ayah: 61, text: "وما تكون في شأن وما تتلوا منه" },
  { thumn: 173, surahNumber: 10, ayah: 71, text: "واتل عليهم نبأ نوح إذ قال لقومه يا قوم" },
  { thumn: 174, surahNumber: 10, ayah: 83, text: "فما آمن لموسى إلا ذرية من قومه" },
  { thumn: 175, surahNumber: 10, ayah: 93, text: "ولقد بوأنا بني إسرائيل مبوأ صدق" },
  { thumn: 176, surahNumber: 10, ayah: 104, text: "قل يا أيها الناس إن كنتم في شك من ديني" },
  { thumn: 177, surahNumber: 11, ayah: 6, text: "وما من دابة في الأرض إلا على الله رزقها" },
  { thumn: 178, surahNumber: 11, ayah: 15, text: "من كان يريد الحياة الدنيا وزينتها" },
  { thumn: 179, surahNumber: 11, ayah: 24, text: "مثل الفريقين كالأعمى والأصم" },
  { thumn: 180, surahNumber: 11, ayah: 32, text: "قالوا يا نوح قد جادلتنا فأكثرت جدالنا" },
  { thumn: 181, surahNumber: 11, ayah: 41, text: "وقال اركبوا فيها بسم الله مجراها" },
  { thumn: 182, surahNumber: 11, ayah: 50, text: "وإلى عاد أخاهم هودا قال يا قوم اعبدوا الله" },
  { thumn: 183, surahNumber: 11, ayah: 62, text: "قالوا يا صالح قد كنت فينا مرجوا قبل هذا" },
  { thumn: 184, surahNumber: 11, ayah: 74, text: "فلما ذهب عن إبراهيم الروع" },
  { thumn: 185, surahNumber: 11, ayah: 84, text: "وإلى مدين أخاهم شعيبا قال يا يقوم" },
  { thumn: 186, surahNumber: 11, ayah: 94, text: "ولما جا أمرنا نجينا شعيبا والذين آمنوا" },
  { thumn: 187, surahNumber: 11, ayah: 105, text: "يوم يأتي لا تكلم نفس إلا بإذنه" },
  { thumn: 188, surahNumber: 11, ayah: 120, text: "وكلا نقص عليك من أنباء الرسل ما نثبت" },
  { thumn: 189, surahNumber: 12, ayah: 10, text: "قال قآئل منهم لا تقتلوا يوسف وألقوه في غيابات الجب" },
  { thumn: 190, surahNumber: 12, ayah: 22, text: "ولما بلغ أشده آتيناه حكما وعلما" },
  { thumn: 191, surahNumber: 12, ayah: 33, text: "قال رب السجن أحب إلي مما يدعونني إليه" },
  { thumn: 192, surahNumber: 12, ayah: 43, text: "وقال الملك إني أرى سبع بقرات سمان" },
  { thumn: 193, surahNumber: 12, ayah: 53, text: "وما أبرئ نفسي إن النفس لأمارة بالسو" },
  { thumn: 194, surahNumber: 12, ayah: 67, text: "وقال يا بني لا تدخلوا من باب واحد" },
  { thumn: 195, surahNumber: 12, ayah: 77, text: "قالوا إن يسرق فقد سرق أخ له من قبل" },
  { thumn: 196, surahNumber: 12, ayah: 88, text: "فلما دخلوا عليه قالوا يا أيها العزيز مسنا" },
  { thumn: 197, surahNumber: 12, ayah: 101, text: "رب قد آتيتني من الملك وعلمتني" },
  { thumn: 198, surahNumber: 12, ayah: 110, text: "حتى إذا استيأس الرسل وظنوا أنهم قد كذبوا" },
  { thumn: 199, surahNumber: 13, ayah: 5, text: "وإن تعجب فعجب قولهم" },
  { thumn: 200, surahNumber: 13, ayah: 16, text: "قل من رب السماوات والأرض قل الله" },
  { thumn: 201, surahNumber: 13, ayah: 19, text: "أفمن يعلم أنما أنزل إليك من ربك الحق" },
  { thumn: 202, surahNumber: 13, ayah: 30, text: "كذلك أرسلناك في أمة قد خلت من قبلها" },
  { thumn: 203, surahNumber: 13, ayah: 35, text: "مثل الجنة التي وعد المتقون" },
  { thumn: 204, surahNumber: 14, ayah: 1, text: "ألر كتاب أنزلناه إليك لتخرج الناس" },
  { thumn: 205, surahNumber: 14, ayah: 10, text: "قالت رسلهم أفي الله شك فاطر" },
  { thumn: 206, surahNumber: 14, ayah: 19, text: "ألم تر أن الله خلق السماوات والأرض" },
  { thumn: 207, surahNumber: 14, ayah: 28, text: "ألم تر إلى الذين بدلوا نعمة الله كفرا" },
  { thumn: 208, surahNumber: 14, ayah: 39, text: "الحمد لله الذي وهب لي على الكبر" },
  { thumn: 209, surahNumber: 15, ayah: 1, text: "ألر تلك آيات الكتاب وقرآن مبين ربما يود" },
  { thumn: 210, surahNumber: 15, ayah: 26, text: "ولقد خلقنا الإنسان من صلصال من حمإ" },
  { thumn: 211, surahNumber: 15, ayah: 49, text: "نبئ عبادي أني أنا الغفور الرحيم" },
  { thumn: 212, surahNumber: 15, ayah: 80, text: "ولقد كذب أصحاب الحجر المرسلين" },
  { thumn: 213, surahNumber: 16, ayah: 1, text: "أتى أمر الله فلا تستعجلوه" },
  { thumn: 214, surahNumber: 16, ayah: 15, text: "وألقى في الأرض رواسي أن تميد بكم" },
  { thumn: 215, surahNumber: 16, ayah: 30, text: "وقيل للذين اتقوا ماذا أنزل ربكم" },
  { thumn: 216, surahNumber: 16, ayah: 38, text: "وأقسموا بالله جهد أيمانهم لا يبعث الله" },
  { thumn: 217, surahNumber: 16, ayah: 51, text: "وقال الله لا تتخذوا إلهين اثنين" },
  { thumn: 218, surahNumber: 16, ayah: 63, text: "تالله لقد أرسلنا إلى أمم من قبلك فزين" },
  { thumn: 219, surahNumber: 16, ayah: 71, text: "والله فضل بعضكم على بعض في الرزق" },
  { thumn: 220, surahNumber: 16, ayah: 79, text: "ألم يروا إلى الطير مسخرات" },
  { thumn: 221, surahNumber: 16, ayah: 90, text: "إن الله يأمر بالعدل والإحسان" },
  { thumn: 222, surahNumber: 16, ayah: 98, text: "فإذا قرأت القرآن فاستعذ بالله" },
  { thumn: 223, surahNumber: 16, ayah: 111, text: "يوم تأتي كل نفس تجادل عن نفسها" },
  { thumn: 224, surahNumber: 16, ayah: 120, text: "إن إبراهيم كان أمة قانتا لله" },
  { thumn: 225, surahNumber: 17, ayah: 1, text: "سبحان الذي أسرى بعبده ليلا" },
  { thumn: 226, surahNumber: 17, ayah: 11, text: "ويدع الإنسان بالشر دعاءه بالخير" },
  { thumn: 227, surahNumber: 17, ayah: 23, text: "وقضى ربك ألا تعبدوا إلا إياه" },
  { thumn: 228, surahNumber: 17, ayah: 36, text: "ولا تقف ما ليس لك به علم" },
  { thumn: 229, surahNumber: 17, ayah: 50, text: "قل كونوا حجارة أو حديدا" },
  { thumn: 230, surahNumber: 17, ayah: 61, text: "وإذ قلنا للملائكة اسجدوا لآدم فسجدوا" },
  { thumn: 231, surahNumber: 17, ayah: 70, text: "ولقد كرمنا بني آدم وحملناهم في البر" },
  { thumn: 232, surahNumber: 17, ayah: 85, text: "ويسألونك عن الروح" },
  { thumn: 233, surahNumber: 17, ayah: 99, text: "أولم يروا أن الله الذي خلق السماوات" },
  { thumn: 234, surahNumber: 18, ayah: 1, text: "الحمد لله الذي أنزل على عبده الكتاب" },
  { thumn: 235, surahNumber: 18, ayah: 17, text: "وترى الشمس إذا طلعت تزاور عن كهفهم" },
  { thumn: 236, surahNumber: 18, ayah: 22, text: "فلا تمار فيهم إلا مراء ظاهرا" },
  { thumn: 237, surahNumber: 18, ayah: 32, text: "واضرب لهم مثلا رجلين جعلنا لأحدهما" },
  { thumn: 238, surahNumber: 18, ayah: 45, text: "واضرب لهم مثل الحياة الدنيا كماء أنزلناه" },
  { thumn: 239, surahNumber: 18, ayah: 54, text: "ولقد صرفنا في هذا القرآن للناس من كل مثل" },
  { thumn: 240, surahNumber: 18, ayah: 64, text: "قال ذلك ما كنا نبغ فارتدا على آثارهما قصصا" },
  { thumn: 241, surahNumber: 18, ayah: 75, text: "قال ألم أقل لك إنك لن تستطيع معي صبرا" },
  { thumn: 242, surahNumber: 18, ayah: 83, text: "ويسألونك عن ذي القرنين قل سأتلوا عليكم منه ذكرا" },
  { thumn: 243, surahNumber: 18, ayah: 99, text: "وتركنا بعضهم يومئذ يموج في بعض" },
  { thumn: 244, surahNumber: 19, ayah: 1, text: "كهيعص ذكر رحمة ربك عبده زكرياء" },
  { thumn: 245, surahNumber: 19, ayah: 22, text: "فحملته فانتبذت به مكانا قصيا" },
  { thumn: 246, surahNumber: 19, ayah: 41, text: "واذكر في الكتاب إبراهيم إنه كان صديقا نبيئا" },
  { thumn: 247, surahNumber: 19, ayah: 59, text: "فخلف من بعدهم خلف أضاعوا الصلاة" },
  { thumn: 248, surahNumber: 19, ayah: 77, text: "أفرأيت الذي كفر بآياتنا وقال لأوتين مالا وولدا" },
  { thumn: 249, surahNumber: 20, ayah: 1, text: "طه ما أنزلنا عليك القرآن لتشقى" },
  { thumn: 250, surahNumber: 20, ayah: 25, text: "قال رب اشرح لي صدري" },
  { thumn: 251, surahNumber: 20, ayah: 55, text: "منها خلقناكم وفيها نعيدكم ومنها" },
  { thumn: 252, surahNumber: 20, ayah: 72, text: "قالوا لن نؤثرك على ما جاءنا من البينات" },
  { thumn: 253, surahNumber: 20, ayah: 83, text: "وما أعجلك عن قومك يا موسى" },
  { thumn: 254, surahNumber: 20, ayah: 95, text: "قال فما خطبك يا سامري" },
  { thumn: 255, surahNumber: 20, ayah: 111, text: "وعنت الوجوه للحي القيوم" },
  { thumn: 256, surahNumber: 20, ayah: 128, text: "أفلم يهد لهم كم أهلكنا قبلهم من القرون" },
  { thumn: 257, surahNumber: 21, ayah: 1, text: "اقترب للناس حسابهم وهم في غفلة" },
  { thumn: 258, surahNumber: 21, ayah: 16, text: "وما خلقنا السماء والأرض وما بينهما لاعبين" },
  { thumn: 259, surahNumber: 21, ayah: 30, text: "أولم ير الذين كفروا أن السماوات والأرض" },
  { thumn: 260, surahNumber: 21, ayah: 42, text: "قل من يكلؤكم بالليل والنهار من الرحمن" },
  { thumn: 261, surahNumber: 21, ayah: 51, text: "ولقد آتينا إبراهيم رشده من قبل" },
  { thumn: 262, surahNumber: 21, ayah: 74, text: "ولوطا آتيناه حكما وعلما" },
  { thumn: 263, surahNumber: 21, ayah: 87, text: "وذا النون إذ ذهب مغاضبا" },
  { thumn: 264, surahNumber: 21, ayah: 101, text: "إن الذين سبقت لهم منا الحسنى" },
  { thumn: 265, surahNumber: 22, ayah: 1, text: "يا أيها الناس اتقوا ربكم إن زلزلة الساعة" },
  { thumn: 266, surahNumber: 22, ayah: 11, text: "ومن الناس من يعبد الله على حرف" },
  { thumn: 267, surahNumber: 22, ayah: 19, text: "هذان خصمان اختصموا في ربهم" },
  { thumn: 268, surahNumber: 22, ayah: 30, text: "ذلك ومن يعظم حرمات الله فهو خير له" },
  { thumn: 269, surahNumber: 22, ayah: 38, text: "إن الله يدافع عن الذين آمنوا" },
  { thumn: 270, surahNumber: 22, ayah: 49, text: "قل يا أيها الناس إنما أنا لكم نذير مبين" },
  { thumn: 271, surahNumber: 22, ayah: 60, text: "ذلك ومن عاقب بمثل ما عوقب به" },
  { thumn: 272, surahNumber: 22, ayah: 70, text: "ألم تعلم أن الله يعلم ما في السماء والأرض" },
  { thumn: 273, surahNumber: 23, ayah: 1, text: "قد أفلح المؤمنون" },
  { thumn: 274, surahNumber: 23, ayah: 21, text: "وإن لكم في الأنعام لعبرة" },
  { thumn: 275, surahNumber: 23, ayah: 36, text: "هيهات هيهات لما توعدون" },
  { thumn: 276, surahNumber: 23, ayah: 57, text: "إن الذين هم من خشية ربهم مشفقون" },
  { thumn: 277, surahNumber: 23, ayah: 75, text: "ولو رحمناهم وكشفنا ما بهم من ضر" },
  { thumn: 278, surahNumber: 23, ayah: 97, text: "وقل رب أعوذ بك من همزات الشياطين" },
  { thumn: 279, surahNumber: 23, ayah: 115, text: "أفحسبتم أنما خلقناكم عبثا وأنكم" },
  { thumn: 280, surahNumber: 24, ayah: 11, text: "إن الذين جاءوا بالإفك عصبة منكم" },
  { thumn: 281, surahNumber: 24, ayah: 21, text: "يا أيها الذين آمنوا لا تتبعوا خطوات الشيطان" },
  { thumn: 282, surahNumber: 24, ayah: 30, text: "قل للمؤمنين يغضوا من أبصارهم" },
  { thumn: 283, surahNumber: 24, ayah: 35, text: "الله نور السماوات والأرض" },
  { thumn: 284, surahNumber: 24, ayah: 43, text: "ألم تر أن الله يزجي سحابا ثم يؤلف بينه" },
  { thumn: 285, surahNumber: 24, ayah: 53, text: "وأقسموا بالله جهد أيمانهم لئن أمرتهم ليخرجن" },
  { thumn: 286, surahNumber: 24, ayah: 60, text: "والقواعد من النساء اللاتي لا يرجون نكاحا" },
  { thumn: 287, surahNumber: 24, ayah: 63, text: "لا تجعلوا دعاء الرسول بينكم كدعاء" },
  { thumn: 288, surahNumber: 25, ayah: 10, text: "تبارك الذي إن شاء جعل لك خيرا من ذلك" },
  { thumn: 289, surahNumber: 25, ayah: 21, text: "وقال الذين لا يرجون لقاءنا لولا أنزل" },
  { thumn: 290, surahNumber: 25, ayah: 32, text: "وقال الذين كفروا لولا نزل عليه القرآن جملة" },
  { thumn: 291, surahNumber: 25, ayah: 45, text: "ألم تر إلى ربك كيف مد الظل" },
  { thumn: 292, surahNumber: 25, ayah: 61, text: "تبارك الذي جعل في السماء بروجا" },
  { thumn: 293, surahNumber: 26, ayah: 1, text: "طسم تلك آيات الكتاب المبين لعلك باخع نفسك" },
  { thumn: 294, surahNumber: 26, ayah: 23, text: "قال فرعون وما رب العالمين" },
  { thumn: 295, surahNumber: 26, ayah: 50, text: "قالوا لا ضير إنا إلى ربنا منقلبون" },
  { thumn: 296, surahNumber: 26, ayah: 78, text: "الذي خلقني فهو يهدين" },
  { thumn: 297, surahNumber: 26, ayah: 111, text: "قالوا أنؤمن لك واتبعك الأرذلون" },
  { thumn: 298, surahNumber: 26, ayah: 146, text: "أتتركون في ما هاهنا آمنين" },
  { thumn: 299, surahNumber: 26, ayah: 181, text: "أوفوا الكيل ولا تكونوا من المخسرين" },
  { thumn: 300, surahNumber: 26, ayah: 208, text: "وما أهلكنا من قرية إلا لها منذرون" },
  { thumn: 301, surahNumber: 27, ayah: 6, text: "وإنك لتلقى القرآن من لدن حكيم عليم" },
  { thumn: 302, surahNumber: 27, ayah: 18, text: "حتى إذ أتوا على واد النمل قالت نملة" },
  { thumn: 303, surahNumber: 27, ayah: 27, text: "قال سننظر أصدقت أم كنت من الكاذبين" },
  { thumn: 304, surahNumber: 27, ayah: 41, text: "قال نكروا لها عرشها" },
  { thumn: 305, surahNumber: 27, ayah: 59, text: "قل الحمد لله وسلام على عباده الذين اصطفى" },
  { thumn: 306, surahNumber: 27, ayah: 67, text: "وقال الذين كفروا إذا كنا ترابا وآباؤنا" },
  { thumn: 307, surahNumber: 27, ayah: 82, text: "وإذا وقع القول عليهم أخرجنا لهم دابة" },
  { thumn: 308, surahNumber: 28, ayah: 1, text: "طسم تلك آيات الكتاب المبين نتلو عليك" },
  { thumn: 309, surahNumber: 28, ayah: 12, text: "وحرمنا عليه المراضع من قبل" },
  { thumn: 310, surahNumber: 28, ayah: 20, text: "وجاء رجل من أقصا المدينة يسعى" },
  { thumn: 311, surahNumber: 28, ayah: 29, text: "فلما قضى موسى الأجل وسار بأهله" },
  { thumn: 312, surahNumber: 28, ayah: 38, text: "وقال فرعون يا أيها الملأ ما علمت لكم" },
  { thumn: 313, surahNumber: 28, ayah: 51, text: "ولقد وصلنا لهم القول لعلهم يذكرون" },
  { thumn: 314, surahNumber: 28, ayah: 61, text: "أفمن وعدناه وعدا حسنا فهو لاقيه" },
  { thumn: 315, surahNumber: 28, ayah: 76, text: "إن قارون كان من قوم موسى" },
  { thumn: 316, surahNumber: 28, ayah: 83, text: "تلك الدار الآخرة نجعلها للذين لا يريدون" },
  { thumn: 317, surahNumber: 29, ayah: 8, text: "ووصينا الإنسان بوالديه حسنا وإن جاهداك" },
  { thumn: 318, surahNumber: 29, ayah: 16, text: "وإبراهيم إذ قال لقومه اعبدوا الله واتقوه" },
  { thumn: 319, surahNumber: 29, ayah: 26, text: "فآمن له لوط" },
  { thumn: 320, surahNumber: 29, ayah: 36, text: "وإلى مدين أخاهم شعيبا" },
  { thumn: 321, surahNumber: 29, ayah: 46, text: "ولا تجادلوا أهل الكتاب إلا بالتي هي أحسن" },
  { thumn: 322, surahNumber: 29, ayah: 60, text: "وكأين من دابة لا تحمل رزقها الله يرزقها وإياكم" },
  { thumn: 323, surahNumber: 30, ayah: 9, text: "أولم يسيروا في الأرض فينظروا كيف" },
  { thumn: 324, surahNumber: 30, ayah: 22, text: "ومن آياته خلق السماوات والأرض واختلاف" },
  { thumn: 325, surahNumber: 30, ayah: 31, text: "منيبين إليه واتقوه وأقيموا الصلاة" },
  { thumn: 326, surahNumber: 30, ayah: 41, text: "ظهر الفساد في البر والبحر" },
  { thumn: 327, surahNumber: 30, ayah: 54, text: "الله الذي خلقكم من ضعف" },
  { thumn: 328, surahNumber: 31, ayah: 12, text: "ولقد آتينا لقمان الحكمة أن أشكر لله" },
  { thumn: 329, surahNumber: 31, ayah: 22, text: "ومن يسلم وجهه لله وهو محسن" },
  { thumn: 330, surahNumber: 31, ayah: 32, text: "وإذا غشيهم موج كالظلل دعوا الله" },
  { thumn: 331, surahNumber: 32, ayah: 11, text: "قل يتوفاكم ملك الموت الذي وكل بكم" },
  { thumn: 332, surahNumber: 32, ayah: 23, text: "ولقد آتينا موسى الكتاب فلا تكن في مرية" },
  { thumn: 333, surahNumber: 33, ayah: 6, text: "النبيء أولى بالمؤمنين من أنفسهم" },
  { thumn: 334, surahNumber: 33, ayah: 13, text: "وإذ قالت طائفة منهم يا أهل يثرب" },
  { thumn: 335, surahNumber: 33, ayah: 20, text: "يحسبون الأحزاب لم يذهبوا" },
  { thumn: 336, surahNumber: 33, ayah: 28, text: "يا أيها النبيء قل لأزواجك إن كنتن تردن" },
  { thumn: 337, surahNumber: 33, ayah: 35, text: "إن المسلمين والمسلمات والمؤمنين" },
  { thumn: 338, surahNumber: 33, ayah: 40, text: "ما كان محمد أبا أحد من رجالكم" },
  { thumn: 339, surahNumber: 33, ayah: 51, text: "ترجي من تشاء منهن" },
  { thumn: 340, surahNumber: 33, ayah: 55, text: "لا جناح عليهن في آباءهن ولا أبنائهن" },
  { thumn: 341, surahNumber: 33, ayah: 60, text: "لئن لم ينته المنافقون والذين في قلوبهم" },
  { thumn: 342, surahNumber: 33, ayah: 72, text: "إنا عرضنا الأمانة على السماوات والأرض" },
  { thumn: 343, surahNumber: 34, ayah: 7, text: "وقال الذين كفروا هل ندلكم على رجل" },
  { thumn: 344, surahNumber: 34, ayah: 15, text: "لقد كان لسبإ في مساكنهم آية" },
  { thumn: 345, surahNumber: 34, ayah: 24, text: "قل من يرزقكم من السماوات والأرض قل الله" },
  { thumn: 346, surahNumber: 34, ayah: 34, text: "وما أرسلنا في قرية من نذير إلا قال مترفوها" },
  { thumn: 347, surahNumber: 34, ayah: 46, text: "قل إنما أعظكم بواحدة" },
  { thumn: 348, surahNumber: 35, ayah: 5, text: "يا أيها الناس إن وعد الله حق" },
  { thumn: 349, surahNumber: 35, ayah: 15, text: "يا أيها الناس أنتم الفقراء إلى الله" },
  { thumn: 350, surahNumber: 35, ayah: 31, text: "والذي أوحينا إليك من الكتاب هو الحق" },
  { thumn: 351, surahNumber: 35, ayah: 40, text: "قل أرأيتم شركاءكم الذين تدعون" },
  { thumn: 352, surahNumber: 36, ayah: 1, text: "يس والقرآن الحكيم" },
  { thumn: 353, surahNumber: 36, ayah: 28, text: "وما أنزلنا على قومه من بعده من جند" },
  { thumn: 354, surahNumber: 36, ayah: 45, text: "وإذا قيل لهم اتقوا ما بين أيديكم" },
  { thumn: 355, surahNumber: 36, ayah: 60, text: "ألم أعهد إليكم يا بني آدم" },
  { thumn: 356, surahNumber: 36, ayah: 77, text: "أولم ير الإنسان أنا خلقناه من نطفة" },
  { thumn: 357, surahNumber: 37, ayah: 22, text: "احشروا الذين ظلموا وأزواجهم" },
  { thumn: 358, surahNumber: 37, ayah: 51, text: "قال قائل منهم إني كان لي قرين" },
  { thumn: 359, surahNumber: 37, ayah: 83, text: "وإن من شيعته لإبراهيم" },
  { thumn: 360, surahNumber: 37, ayah: 114, text: "ولقد مننا على موسى وهارون" },
  { thumn: 361, surahNumber: 37, ayah: 145, text: "فنبذناه بالعراء وهو سقيم" },
  { thumn: 362, surahNumber: 38, ayah: 1, text: "ص والقرآن ذي الذكر" },
  { thumn: 363, surahNumber: 38, ayah: 21, text: "وهل أتاك نبأ الخصم إذ تسورا المحراب" },
  { thumn: 364, surahNumber: 38, ayah: 30, text: "ووهبنا لداوود سليمان" },
  { thumn: 365, surahNumber: 38, ayah: 52, text: "وعندهم قاصرات الطرف أتراب" },
  { thumn: 366, surahNumber: 38, ayah: 84, text: "قال فالحق والحق أقول" },
  { thumn: 367, surahNumber: 39, ayah: 8, text: "وإذا مس الإنسان ضر دعا ربه منيبا إليه" },
  { thumn: 368, surahNumber: 39, ayah: 19, text: "أفمن حق عليه كلمة العذاب" },
  { thumn: 369, surahNumber: 39, ayah: 32, text: "فمن أظلم ممن كذب على الله وكذب بالصدق" },
  { thumn: 370, surahNumber: 39, ayah: 43, text: "أم اتخذوا من دون الله شفعاء" },
  { thumn: 371, surahNumber: 39, ayah: 53, text: "قل يا عبادي الذي أسرفوا على أنفسهم" },
  { thumn: 372, surahNumber: 39, ayah: 67, text: "وما قدروا الله حق قدره والأرض جميعا" },
  { thumn: 373, surahNumber: 40, ayah: 1, text: "حم تنزيل الكتاب من الله العزيز العليم" },
  { thumn: 374, surahNumber: 40, ayah: 10, text: "إن الذين كفروا ينادون لمقت الله أكبر" },
  { thumn: 375, surahNumber: 40, ayah: 21, text: "أولم يسيروا في الأرض فينظروا كيف" },
  { thumn: 376, surahNumber: 40, ayah: 30, text: "وقال الذي آمن يا قوم إني أخاف عليكم" },
  { thumn: 377, surahNumber: 40, ayah: 41, text: "ويا قومي مالي أدعوكم إلى النجاة" },
  { thumn: 378, surahNumber: 40, ayah: 53, text: "ولقد آتينا موسى الهدى وأورثنا" },
  { thumn: 379, surahNumber: 40, ayah: 66, text: "قل إني نهيت أن أعبد الذي تدعون" },
  { thumn: 380, surahNumber: 40, ayah: 79, text: "الله الذي جعل لكم الأنعام لتركبوا منها" },
  { thumn: 381, surahNumber: 41, ayah: 9, text: "قل أإنكم لتكفرون بالذي خلق الأرض في يومين" },
  { thumn: 382, surahNumber: 41, ayah: 17, text: "وأما ثمود فهديناهم فاستحبوا العمى" },
  { thumn: 383, surahNumber: 41, ayah: 26, text: "وقال الذين كفروا لا تسمعوا لهذا القرآن" },
  { thumn: 384, surahNumber: 41, ayah: 38, text: "فإن استكبروا فالذين عند ربك يسبحون" },
  { thumn: 385, surahNumber: 41, ayah: 47, text: "إليه يرد علم الساعة" },
  { thumn: 386, surahNumber: 42, ayah: 1, text: "حم عسق كذلك يوحي إليك" },
  { thumn: 387, surahNumber: 42, ayah: 13, text: "شرع لكم من الدين ما وصى به نوحا" },
  { thumn: 388, surahNumber: 42, ayah: 21, text: "أم لهم شركاء شرعوا لهم من الدين" },
  { thumn: 389, surahNumber: 42, ayah: 34, text: "أو يوبقهن بما كسبوا ويعف عن كثير" },
  { thumn: 390, surahNumber: 42, ayah: 43, text: "ولمن صبر وغفر إن ذلك لمن عزم الأمور" },
  { thumn: 391, surahNumber: 42, ayah: 51, text: "وما كان لبشر أن يكلمه الله إلا وحيا" },
  { thumn: 392, surahNumber: 43, ayah: 12, text: "والذي خلق الأزواج كلها" },
  { thumn: 393, surahNumber: 43, ayah: 24, text: "قل أولو جئتكم بأهدى مما وجدتم عليه آباءكم" },
  { thumn: 394, surahNumber: 43, ayah: 43, text: "فاستمسك بالذي أوحي إليك" },
  { thumn: 395, surahNumber: 43, ayah: 63, text: "ولما جاء عيسى بالبينات قال قد جئتكم" },
  { thumn: 396, surahNumber: 43, ayah: 84, text: "وهو الذي في السماء إله وفي الأرض إله" },
  { thumn: 397, surahNumber: 44, ayah: 25, text: "كم تركوا من جنات وعيون وزروع" },
  { thumn: 398, surahNumber: 44, ayah: 51, text: "إن المتقين في مقام أمين" },
  { thumn: 399, surahNumber: 45, ayah: 11, text: "هذا هدى والذين كفروا بآيات ربهم" },
  { thumn: 400, surahNumber: 45, ayah: 23, text: "أفرأيت من اتخذ إلهه هواه" },
  { thumn: 401, surahNumber: 46, ayah: 1, text: "حم تنزيل الكتاب من الله العزيز الحكيم" },
  { thumn: 402, surahNumber: 46, ayah: 15, text: "ووصينا الإنسان بوالديه حسنا" },
  { thumn: 403, surahNumber: 46, ayah: 21, text: "واذكر أخا عاد إذ أنذر قومه بالأحقاف" },
  { thumn: 404, surahNumber: 46, ayah: 33, text: "أولم يروا أن الله الذي خلق السماوات" },
  { thumn: 405, surahNumber: 47, ayah: 10, text: "أفلم يسيروا في الأرض فينظروا كيف" },
  { thumn: 406, surahNumber: 47, ayah: 20, text: "ويقول الذين آمنوا لولا نزلت سورة" },
  { thumn: 407, surahNumber: 47, ayah: 33, text: "يا أيها الذين آمنوا أطيعوا الله وأطيعوا الرسول" },
  { thumn: 408, surahNumber: 48, ayah: 8, text: "إنا أرسلناك شاهدا ومبشرا ونذيرا" },
  { thumn: 409, surahNumber: 48, ayah: 18, text: "لقد رضي الله عن المؤمنين إذ يبايعونك" },
  { thumn: 410, surahNumber: 48, ayah: 27, text: "لقد صدق الله رسوله الرؤيا بالحق" },
  { thumn: 411, surahNumber: 49, ayah: 1, text: "يا أيها الذين آمنوا لا تقدموا بين يدي الله" },
  { thumn: 412, surahNumber: 49, ayah: 9, text: "وإن طائفتان من المؤمنين اقتتلوا" },
  { thumn: 413, surahNumber: 49, ayah: 14, text: "قالت الأعراب آمنا" },
  { thumn: 414, surahNumber: 50, ayah: 6, text: "أفلم ينظروا إلى السماء فوقهم" },
  { thumn: 415, surahNumber: 50, ayah: 27, text: "قال قرينه ربنا ما أطغيته" },
  { thumn: 416, surahNumber: 51, ayah: 1, text: "والذاريات ذروا" },
  { thumn: 417, surahNumber: 51, ayah: 31, text: "قال فما خطبكم أيها المرسلون" },
  { thumn: 418, surahNumber: 51, ayah: 56, text: "وما خلقت الجن والإنس إلا ليعبدون" },
  { thumn: 419, surahNumber: 52, ayah: 24, text: "ويطوف عليهم غلمان لهم كأنهم لؤلؤ مكنون" },
  { thumn: 420, surahNumber: 52, ayah: 44, text: "وإن يروا كسفا من السماء ساقطا" },
  { thumn: 421, surahNumber: 53, ayah: 26, text: "وكم من ملك في السماوات لا تغني شفاعتهم" },
  { thumn: 422, surahNumber: 53, ayah: 56, text: "هذا نذير من النذر الأولى" },
  { thumn: 423, surahNumber: 54, ayah: 18, text: "كذبت عاد فكيف كان عذابي ونذر" },
  { thumn: 424, surahNumber: 54, ayah: 41, text: "ولقد جا آل فرعون النذر" },
  { thumn: 425, surahNumber: 55, ayah: 1, text: "الرحمن علم القرآن" },
  { thumn: 426, surahNumber: 55, ayah: 33, text: "يا معشر الجن والإنس إن استطعتم" },
  { thumn: 427, surahNumber: 55, ayah: 60, text: "هل جزاء الإحسان إلا الإحسان" },
  { thumn: 428, surahNumber: 56, ayah: 27, text: "وأصحاب اليمين" },
  { thumn: 429, surahNumber: 56, ayah: 75, text: "فلا أقسم بمواقع النجوم" },
  { thumn: 430, surahNumber: 57, ayah: 7, text: "آمنوا بالله ورسوله وأنفقوا مما جعلكم" },
  { thumn: 431, surahNumber: 57, ayah: 16, text: "ألم يأن للذين آمنوا أن تخشع قلوبهم" },
  { thumn: 432, surahNumber: 57, ayah: 22, text: "ما أصاب من مصيبة في الأرض" },
  { thumn: 433, surahNumber: 58, ayah: 1, text: "قد سمع الله قول التي تجادلك في زوجها" },
  { thumn: 434, surahNumber: 58, ayah: 8, text: "ألم تر إلى الذين نهوا عن النجوى" },
  { thumn: 435, surahNumber: 58, ayah: 14, text: "ألم تر إلى الذين تولوا قوما غضب الله عليهم" },
  { thumn: 436, surahNumber: 59, ayah: 1, text: "سبح لله ما في السماوات وما في الأرض" },
  { thumn: 437, surahNumber: 59, ayah: 11, text: "ألم تر إلى الذين نافقوا يقولون لإخوانهم" },
  { thumn: 438, surahNumber: 60, ayah: 1, text: "يا أيها الذين آمنوا لا تتخذوا عدوي" },
  { thumn: 439, surahNumber: 60, ayah: 7, text: "عسى الله أن يجعل بينكم وبين الذين عاديتم" },
  { thumn: 440, surahNumber: 61, ayah: 1, text: "سبح لله ما في السماوات وما في الأرض" },
  { thumn: 441, surahNumber: 62, ayah: 1, text: "يسبح لله ما في السماوات وما في الأرض" },
  { thumn: 442, surahNumber: 62, ayah: 9, text: "يا أيها الذين آمنوا إذا نودي للصلاة" },
  { thumn: 443, surahNumber: 63, ayah: 9, text: "يا أيها الذين آمنوا لا تلهكم أموالكم ولا أولادكم" },
  { thumn: 444, surahNumber: 64, ayah: 7, text: "زعم الذين كفروا أن لن يبعثوا" },
  { thumn: 445, surahNumber: 64, ayah: 14, text: "يا أيها الذين آمنوا إن من أزواجكم" },
  { thumn: 446, surahNumber: 65, ayah: 6, text: "اسكنوهن من حيث سكنتم من وجدتكم" },
  { thumn: 447, surahNumber: 65, ayah: 12, text: "الله الذي خلق سبع سماوات ومن الأرض مثلهن" },
  { thumn: 448, surahNumber: 66, ayah: 8, text: "يا أيها الذين آمنوا توبوا إلى الله" },
  { thumn: 449, surahNumber: 67, ayah: 1, text: "تبارك الذي بيده الملك" },
  { thumn: 450, surahNumber: 67, ayah: 19, text: "أولم يروا إلى الطير فوقهم صافات" },
  { thumn: 451, surahNumber: 68, ayah: 19, text: "فطاف عليها طائف من ربك" },
  { thumn: 452, surahNumber: 69, ayah: 1, text: "الحاقة ما الحاقة" },
  { thumn: 453, surahNumber: 69, ayah: 38, text: "فلا أقسم بما تبصرون وما لا تبصرون" },
  { thumn: 454, surahNumber: 70, ayah: 19, text: "إن الإنسان خلق هلوعا" },
  { thumn: 455, surahNumber: 70, ayah: 40, text: "فلا أقسم برب المشارق والمغارب" },
  { thumn: 456, surahNumber: 71, ayah: 15, text: "ألم تر كيف خلق الله سبع سماوات طباقا" },
  { thumn: 457, surahNumber: 72, ayah: 1, text: "قل أوحي إلى أنه استمع نفر من الجن" },
  { thumn: 458, surahNumber: 72, ayah: 18, text: "وأن المساجد لله فلا تدعو مع الله أحدا" },
  { thumn: 459, surahNumber: 73, ayah: 20, text: "إن ربك يعلم أنك تقوم أدنى من ثلي الليل" },
  { thumn: 460, surahNumber: 74, ayah: 31, text: "وما جعلنا أصحاب النار إلا ملائكة" },
  { thumn: 461, surahNumber: 75, ayah: 1, text: "لا أقسم بيوم القيامة" },
  { thumn: 462, surahNumber: 76, ayah: 1, text: "هل أتى على الإنسان حين من الدهر" },
  { thumn: 463, surahNumber: 76, ayah: 19, text: "ويطوف عليهم ولدان مخلدون" },
  { thumn: 464, surahNumber: 77, ayah: 16, text: "ألم نهلك الأولين" },
  { thumn: 465, surahNumber: 78, ayah: 1, text: "عم يتساءلون" },
  { thumn: 466, surahNumber: 79, ayah: 1, text: "والنازعات غرقا" },
  { thumn: 467, surahNumber: 79, ayah: 42, text: "يسألونك عن الساعة أيان مرساها" },
  { thumn: 468, surahNumber: 80, ayah: 33, text: "فإذا جاءت الصاخة" },
  { thumn: 469, surahNumber: 81, ayah: 15, text: "فلا أقسم بالخنس" },
  { thumn: 470, surahNumber: 83, ayah: 7, text: "كلا إن كتاب الفجار لفي سجين" },
  { thumn: 471, surahNumber: 84, ayah: 16, text: "فلا أقسم بالشفق" },
  { thumn: 472, surahNumber: 85, ayah: 12, text: "إن بطش ربك لشديد" },
  { thumn: 473, surahNumber: 87, ayah: 1, text: "سبح اسم ربك الأعلى" },
  { thumn: 474, surahNumber: 88, ayah: 17, text: "أفلا ينظرون إلى الإبل كيف خلقت" },
  { thumn: 475, surahNumber: 90, ayah: 1, text: "لا أقسم بهذا البلد" },
  { thumn: 476, surahNumber: 92, ayah: 1, text: "والليل إذا يغشى" },
  { thumn: 477, surahNumber: 94, ayah: 1, text: "ألم نشرح لك صدرك" },
  { thumn: 478, surahNumber: 97, ayah: 1, text: "إنا أنزلناه في ليلة القدر" },
  { thumn: 479, surahNumber: 100, ayah: 9, text: "أفلا يعلم إذا بعثر ما في القبور" },
  { thumn: 480, surahNumber: 105, ayah: 1, text: "ألم تر كيف فعل ربك بأصحاب الفيل" },
];

/**
 * يحسب نهاية ثمن معيّن: الآية التي تسبق مباشرة مطلع الثمن التالي (بترتيب المصحف المطلق)، فيعبر تلقائياً
 * حدود السورة إن اقتضى الأمر (نادر، لكن وارد). آخر ثمن (480) ينتهي بآخر آية في القرآن (آخر آية من سورة الناس).
 */
export function getThumnEnd(thumn: number): { surahNumber: number; ayah: number } | null {
  const idx = THUMN_STARTS.findIndex((t) => t.thumn === thumn);
  if (idx === -1) return null;

  const next = THUMN_STARTS[idx + 1];
  if (!next) {
    const lastSurah = SURAHS[SURAHS.length - 1];
    return { surahNumber: lastSurah.number, ayah: lastSurah.totalAyahs };
  }

  if (next.ayah > 1) return { surahNumber: next.surahNumber, ayah: next.ayah - 1 };
  const prevSurah = SURAHS.find((s) => s.number === next.surahNumber - 1);
  return prevSurah
    ? { surahNumber: prevSurah.number, ayah: prevSurah.totalAyahs }
    : { surahNumber: next.surahNumber, ayah: next.ayah };
}
